services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - ./.jellyfin/config:/config
      - ./.jellyfin/cache:/cache
      - /mnt/jellyfin/media/music:/mnt/music
      - /mnt/jellyfin/media/movies:/mnt/movies
      - /mnt/jellyfin/media/tv:/mnt/tv
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.mooserooster.com
  wireguard:
    image: linuxserver/wireguard:latest
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - "51820:51820/udp"
    volumes:
      - ./wireguard:/etc/wireguard/
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d/
      - /etc/ssl/certs:/etc/ssl/certs
  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./certbot:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/log/letsencrypt:/var/log/letsencrypt