http {

  #HTTPS Redirect
  server {
    listen 80;
    server_name _;

    # Redirect to HTTPS
    return 301 https://$host$request_uri;
  }

  # Jellyfin
  server {
    listen 443 ssl;
    server_name jellyfin.mooserooster.com;

    # SSL/TLS settings, adjust as needed
    ssl_certificate /etc/nginx/certs/mooserooster.crt;
    ssl_certificate_key /etc/nginx/certs/mooserooster.key;

    location / {
      proxy_pass http://localhost:8096;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto https;
    }
  }
}
