# Jellyfin
server {
  listen 443 ssl;
  server_name jellyfin.mooserooster.com;

  # SSL/TLS settings, adjust as needed
  ssl_certificate /etc/ssl/certs/mooserooster.crt;
  ssl_certificate_key /etc/ssl/certs/mooserooster.key;

  location / {
    proxy_pass http://localhost:8096;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto https;
  }
}

